### ISSUE TITLE
code example for plug-and-play guidance for diffusion models

### ISSUE THREAD

**Issue by MikeWangWZHL** [ChenWu98/cycle-diffusion#17]
Thanks for this amazing work. 

I wonder where I can find any code example for section 4.3 (plug-and-play guidance for diffusion models) with e.g., stable diffusion? I believe it is not included in the cycle_diffusion pipeline?

Thanks!

**Comment by ChenWu98** [comment]
Sorry for the late reply! The code for plug-and-play guidance is in [this repo](https://github.com/ChenWu98/unified-generative-zoo). However, we have support for LDM (and several other models) but not for Stable Diffusion. Since SD is based on LDM, I think it is definitely possible to apply it to SD.

**Comment by ChenWu98** [comment]
I am closing this issue. Feel free to re-open it if there are any further questions.
