### ISSUE TITLE
Questions with Plug-and-play Guidance

### ISSUE THREAD

**Issue by songwoh** [ChenWu98/cycle-diffusion#26]
Hello, thanks for the great work.
I had some questions with plug-and-play guidance.

(1) In section 3.4, the latent code is updated with langevin dynamics, which includes term for scores for the latent code, z.
I am curious of how to obtain the scores for z.

(2) Also, for me it seems like plug-and-play guidance is exactly the same as classifier guidance if the energy term (CLIP or Face Recognition case) is taking target image + some level of noise as input. Could you explain the difference between the two?

Thank you.

**Comment by ChenWu98** [comment]
Hi, thanks for your questions. 

(1) Our z is not the noisy images, but the concatenation of all Gaussian noises added to each noisy image (i.e., the dimension of z is *the latent dimension of each noisy image* times *the number of denoising steps*). Therefore, p(z) is the isometric Gaussian distribution, whose score is the derivative of log N(z|0, I). 

(2) The plug-and-play guidance is different from classifier guidance in two senses. First, the energy term is computed over clean images in our case, but over noisy images in classifier guidance. Second, in each iteration of Langevin dynamics, we update z (i.e., the concatenation of all Gaussian noises) instead of a noisy image of a particular step. Also, the number of iterations for Langevin dynamics is not necessarily the same as the number of denoising steps for the diffusion model. 

Let me know if my answer is not clear enough.

**Comment by songwoh** [comment]
Your explanation actually cleared up everything for me.
Thank you.
