### ISSUE TITLE
empty.py

### ISSUE THREAD

**Issue by yilinma-97** [ChenWu98/cycle-diffusion#33]
"Could you provide the empty.py script of the translate_ffhq256_to_celeba256 project?"

**Comment by ChenWu98** [comment]
Hi! Could you provide more details about what you’ve run and the error messages?

**Comment by yilinma-97** [comment]
Hello, thank you for your response! I want to use a latent diffusion model for unpaired image-to-image translation. I have the following two questions:

Do I need to train two separate latent diffusion models for the two types of images? If so, which project should I use for training?
In the cycle-diffusion project, how do I input these two datasets? Should they be input in the empty.py script? How does cycle-diffusion distinguish between the two datasets?

**Comment by ChenWu98** [comment]
Hi! Unfortunately, I cannot provide actionable suggestions because we didn't include this experiment in the paper, but here are some high-level ideas: 
- If you have two domains, yes you need to train two latent diffusion models. You may find https://github.com/CompVis/latent-diffusion helpful!
- To use with the repo: the translate_ffhq256_to_celeba256 config is a good place to start! I think empty.py is shared for different scripts -- so if you set the config files correct, it should work with some little tweaks. 

**Disclaimer:** I haven't tested this part as it's not included in our paper.

**Comment by yilinma-97** [comment]
Alright, no problem, I just wanted to try it out. So, how should I pass images from these two domains to cycle-diffusion? Just like the cat and dog experiment in the paper, where do I input the cat images and dog images? I understand that both empty.py and afhqcat256.py in the project are related to image input, but I’ve never quite understood how this works.

**Comment by ChenWu98** [comment]
Hi, I hope the details I provided in issue #9 would be helpful!
