### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data_program'

### ISSUE THREAD

**Issue by chouyunming** [ChenWu98/cycle-diffusion#34]
I just followed [these steps](https://github.com/ChenWu98/cycle-diffusion/issues/9#issuecomment-1317875364) intending to do unpaired img2img task on custom dataset. But I encountered an error as title, is raw_data/empty.py need any modifications ?
Appreciate for any reply !

**Comment by ChenWu98** [comment]
Hi! I guess this happens because the config file is not read by the code successfully. Did you change [this line](https://github.com/ChenWu98/cycle-diffusion/blob/54206c060007d464bbe4c1025ad8303f5f501450/config/experiments/translate_afhqcat256_to_afhqdog256_ddim_eta01.cfg#L20) to point to your config file?
